### ISSUE TITLE
Google Driveでベースデータの調整を行う

### ISSUE THREAD

**Issue by HirokiTakenaka** [IshidaHIRO/SDD3#18]

**Comment by IshidaHIRO** [comment]
@leyosh 
Google Driveに、おにぎり、サラダ、スープのサンプル調査結果を掲載しました。
パン（チョコチップパン・あんぱん）は３社とも山﨑製パンが作っていました。（成分配合は３社とも違います）
おでんはセブンイレブンのみで、価格表（画像）をUPしました。
この方法でよいのかジャッジできないので、一旦レビューお願い致します。
