### ISSUE TITLE
Boot Strap導入

### ISSUE THREAD

**Issue by HirokiTakenaka** [IshidaHIRO/SDD3#21]

**Comment by takahashiko** [comment]
仕切り直しでbootstrapのインストールを行います。
参考サイトは以下の通りです。
http://qiita.com/shizuma/items/83cdadbe0a629f1f74d1

**Comment by tantan5** [comment]
@takahashiko 
#28 で必要だったのでこちらの作業ブランチにsassで暫定的に導入してます。
https://github.com/IshidaHIRO/SDD3/commit/a84129afc1ad30aa71deb30545c1b6d6f0d2446d

重複作業しちゃって申し訳ないです。修正方向が同じであればプルリクして頂いた後にこちらの分はmergeします。

**Comment by tantan5** [comment]
MergedになったのでCloseします。
