### ISSUE TITLE
Twitterからのデータ取得方法の検討

### ISSUE THREAD

**Issue by HirokiTakenaka** [IshidaHIRO/SDD3#23]

**Comment by HirokiTakenaka** [comment]
誰がどこらへんやるか分からなかったので、ひとまずTwitter系の部分もらいます。 @tantan5 さんやりたかったら言ってください。

@leyosh さんが抽出キーワードについて打ち合わせ中に言ってたような気がするのですが、どんな感じでしたっけ？「[コンビニ名]、[商品名]、おいしい」とかでしたっけ？

**Comment by HirokiTakenaka** [comment]
それとも言い出しっぺの@gittkrd さんがやるつもりだったのかな。当方ノウハウがあるわけではないので、立候補あればお譲りしますｗ

**Comment by HirokiTakenaka** [comment]
Twitter APIの使用方法を少し調査しました。
本格的には明日やります。

面白いとおもったのが、ポジティブ検索、ネガティブ検索というものがあり、
独自のアルゴリズム使って感情解析出来るみたいです。
<参考サイト>(https://syncer.jp/twitter-api-matome/get/search/tweets)

実績：0.5h

**Comment by HirokiTakenaka** [comment]
APIやRuby Gemの使用方法を調査し、mdファイルに内容をまとめてpushしました。

実績：2h

**Comment by tantan5** [comment]
あれ、ポジネガ分析って自前のプログラムで解析するのが当たり前だと思ってたんですが、標準でサポートしたんですね。
コンビニ名、商品名、うまい/まずい　打ち合わせではこの条件でしたが、ポジネガが簡単に判定出来るならコンビニ、商品名、ポジ/ネガの方がソーシャル使った評判分析としては一般的かなと思います。
ただ、この辺はPOに確認する必要がありますね。両方書いてみて精度がどうかみないと見ないと判断つかない気がしますが。
（実際にはコンビニ、商品名に付随して出現する頻出単語とかも見ながらチューニングや検討してるはずです。例:口コミ係長）

**Comment by HirokiTakenaka** [comment]
@tantan5 ソーシャルビックデータ分析ツールなんてのを商売にしてるところがあるんですね（口コミ＠係長）。参考になります。
チューニングは色々試してみる必要あるかと思うので、早めにいくつかパターンの結果をまとめてPOからフィードバックもらうようにします。
また、今週私がやれる範囲ですとシンプルなキーワード検索しか実装出来ないと思うので、何か技術的にチャレンジしたい部分などあれば追加作業として取り組んでもらって構いませんので。

**Comment by HirokiTakenaka** [comment]
実績（合計）：2.0h
