### ISSUE TITLE
ユーザヒアリング結果を共有するスプレッドシートを用意する

### ISSUE THREAD

**Issue by HirokiTakenaka** [IshidaHIRO/SDD3#55]
face to faceでヒアリング出来ない人にも聞きやすいように、またヒアリングの質を揃えるため、スプレッドシート展開可能なアンケートフォームを作成したいと思います。

- [x] アンケートフォームを作成
- [x] アンケート項目の項目検討
- [ ] アンケート項目のレビュー

**Comment by HirokiTakenaka** [comment]
アンケートフォームを作成しました。ご意見ください。
２名以上の意見をもらい、反映したらCloseします。

[アンケートフォーム](https://goo.gl/forms/5qDK92gBxxbrkhE62)

**Comment by tantan5** [comment]
色々ありがとうございます。
この手の方式は、今後実現するストーリーの優先度付けには分かりやすいですね。
ただ、今日の議論としては「とにかくユーザー探してこい」「そもそもの方向性探る材料を得る」というところかと思うので、先入観なくフラットに聞いてどんな結果が出るかを見た方が良いのではと思ってます。

**Comment by HirokiTakenaka** [comment]
@tantan5 ご意見ありがとうございます。確かに、細かいアンケートは次の段階だったかもしれないですね。取り急ぎ手応えを得る為にざっくばらんに意見を聞いてみる、という感じなら使用しないでやりましょうか。

**Comment by HirokiTakenaka** [comment]
もう一名くらいご意見を聞いてからCloseしますので、引き続きご意見ください。

**Comment by takahashiko** [comment]
@HirokiTakenaka @tantan5 
いろいろ対応ありがとうございます。また、 @tantan5 のレスポンスが早くてとても助かります。
私も確認してみましたが、ユーザーがこのサービスを使用しての興味があるか、もしくは興味がない場合、サービスの今後の展開にどのユーザーをターゲットにするべきか判断しやすいかと思います。
但し、アンケートだけ答えてもらうだけでなく、実際にサービスを使用してねと感想書いてねとフォローしながら
やらないといけないですね。
アンケート質問内容については、修正すべき点はないので実際に会社の同僚に使用してみます。
今日は出勤なので、聞ける相手がいれば聞いてみますね。

**Comment by HirokiTakenaka** [comment]
@takahashiko 
返信おそくなりすみません。コメントありがとうございます！
@tantan5 さんの意見もありますので、今回は下記のようになるべく使いましょうという扱いが良いですかね。  
* ヒアリング時に厳密にアンケートフォームの構成に従う必要はない
* ただし、「現行サービスについてどう感じるか」、「今後追加されたらうれしい機能（価値）」という軸で質問する
* 回答結果は基本的にアンケートフォームに集約する（または別の方法で共有する）

**Comment by HirokiTakenaka** [comment]
２名のフィードバックが得られたので、ひとまず上記を暫定運用としてCloseします。

**Comment by IshidaHIRO** [comment]
３０代２０代の男子３・女子３に依頼しました
