### ISSUE TITLE
スマートフォン表示の際に価格、カロリー、分量以外の項目はアコーディオンで隠すようにする

### ISSUE THREAD

**Issue by HirokiTakenaka** [IshidaHIRO/SDD3#60]
- [x] アコーディオン表示の方法を調査
- [x] アコーディオン表示の実装

**Comment by HirokiTakenaka** [comment]
## アコーディオン表示の方法
とりあえず今回はBootstrapを使用しているので、下記サイトで紹介されてる方法で良いのかな。  
[Bootstrap3 アコーディオンとCollapseの簡単な使い方](http://designup.jp/bootstrap3-collapse-194/)
[簡単。Bootstrapでアコーディオンパネルを作る方法](http://kishiken.com/bootstrap/collapse.html)  

普通は（？）jQueryで実装するらしい。
[超簡単jQuery！toggle系メソッドでアコーディオンメニューやタブをさくっと実装する方法](https://liginc.co.jp/web/js/jquery/34048)

CSSは少し触ったことあるくらいの経験ですが、実装に着手します。

**Comment by tantan5** [comment]
@HirokiTakenaka 
こちらの作業でViewをHelperに切り出す変更しています。影響ありそうなので先に共有しておきます。
https://github.com/IshidaHIRO/SDD3/blob/emphasizeFirstPlace/app/helpers/welcome_helper.rb

**Comment by HirokiTakenaka** [comment]
@tantan5 
先に共有してもらえるととても助かります。なるほど、helperで横の数値比較を実現しているんですね。勉強になります。
print_productに手を加える必要がありそうなのと、今日明日は作業あまり出来なさそうなので一旦保留します。
