### ISSUE TITLE
ローソンとセブンイレブンのデータ（内容量、塩分、糖質・・・）を表示させる。対象商品は[サラダチキン・サラダ・スープ・梅おにぎり]csvファイル参照）

### ISSUE THREAD

**Issue by IshidaHIRO** [IshidaHIRO/SDD3#63]
誰か手が空いている方にお頼み申す。
（石田、スキル不足ゆえ、断念します。）

**Comment by tantan5** [comment]
@IshidaHIRO 
元ネタのCSVファイルってどちらですか？

**Comment by IshidaHIRO** [comment]
デイリースクラム・振り返りシートにシート名『salad-chicken他』で作成しました。
手元資料ではサラダ（セブンイレブン）については詳細データが不明です。

**Comment by takahashiko** [comment]
@IshidaHIRO @tantan5 @HirokiTakenaka @leyosh @gittkrd 
私がPRしていた #58 #56 が @tantan5 さんのPR適用により私のPRがコンフリクトしたので、私が対応します。
なお、追加サラダチキンについては「ハーブ」のみ追加しました。
※（カレーは３社データになかったので。）
herokuの確認をお願いいたします。
https://arcane-sands-50825.herokuapp.com/

【対応issue】
#58 # 56 #63

**Comment by IshidaHIRO** [comment]
サラダ（ローソンとセブンイレブン）のデータ追加しましたので、ご参考程度ですが、報告します
