### ISSUE TITLE
比較表のUI作成

### ISSUE THREAD

**Issue by HirokiTakenaka** [IshidaHIRO/SDD3#67]
オリジナル比較表を表示する画面のUIラフスケッチを作成します。
- [x] ラフスケッチの作成
- [x] レビュー

**Comment by HirokiTakenaka** [comment]
@leyosh @tantan5 @IshidaHIRO @takahashiko @gittkrd 
ラフスケッチをGoogleドライブに作成しました。
下記について確認をお願いします。
PO＋開発メンバー1名のレビューでOKならCloseします。

[スプレッド](https://docs.google.com/spreadsheets/d/1c_fESuntPMlTxvK921QYCh0u7M2g9Hr4rsGtYm6RwIA/edit?usp=sharing)

[PDF](https://drive.google.com/file/d/0B1Wh4FifWMascEp3dUIxQTAwQ1E/view?usp=sharing)

**Comment by takahashiko** [comment]
@HirokiTakenaka 
ラフ案ありがとうございます！だいぶイメージがついたので助かります。
確認させていて、3点ほど確認したい点がありましたので質問させてください。

1. 評価者のハンドルネームは登録画面でよい？

2.評価者の評価項目は1項目として1行で3社の商品必ず評価しなければならない？
（評価者は必ず3社を食べ比べをしなければいけないかを確認したいので）

3.「いいね！」の評価基準は1投稿（3社の評価に対し妥当と思えば）について同意できれば「いいね！」を押下する理解でOKですか？
※3社の評価が妥当だと思わないと他人は「いいね！」を押さなのでは(数字が伸びないかな)と思ったので。

質問の意図が不明確ならば個別でslackでもハングアウトでもよいので聞いてください。
（私だけ昨日のミーティングで意図を拾えきれなかったみたいで申し訳ございません。）
以上、よろしくお願いいたします。

**Comment by HirokiTakenaka** [comment]
@takahashiko 
さっそく確認ありがとうございます。
土曜時点で私自身はっきりしたイメージを伝えきれていなかった＆詰められていなかったので疑問が生じるのはしょうがないと思います。すみません。

> 評価者のハンドルネームは登録画面でよい？
→必要でした。登録画面に追加します。

> 評価者の評価項目は1項目として1行で3社の商品必ず評価しなければならない？
→現時点では一度に3社評価をしてもらいたいと私は考えています。１行（または1評価者が登録する複数行）がブログとかで書かれる比較記事のマイクロ版のイメージです。こちらについては次回レビューなどでの検討項目としましょう。

> 「いいね！」の評価基準は1投稿（3社の評価に対し妥当と思えば）について同意できれば「いいね！」を押下する理解でOKですか？
→こちらも上記イメージで、3社比較に対する「いいね」を想定しています（３社比較1行単位でのランク付け）。おっしゃるとおりファミマとローソンの評価は参考になるけど、セブンの評価だけ納得いかないから「いいね」しない、などのケースもあるかもしれません。こちらも上記と合わせ次回検討させてもらえればと思います。

**Comment by takahashiko** [comment]
@HirokiTakenaka 
早速のご返事ありがとうございました。
不明確な部分が解消されました。
今回は評価項目およびいいね！は3社の登録、評価ということで理解しました :+1:

**Comment by IshidaHIRO** [comment]
:+1:

**Comment by tantan5** [comment]
確認しました。
結構土曜に受けたイメージとは乖離があって、やっぱりラフに書くの大事ですね。
ありがとうございます。

**Comment by tantan5** [comment]
一点、比較表の入力欄に商品IDが必要かなと思います。
どの商品への比較か今紐付かないので。
今の商品数であればドロップダウンとかで選ぶ形でしょうか。

**Comment by HirokiTakenaka** [comment]
商品との紐づけ必要ですね！失礼しました。
登録画面には商品表示画面から遷移することを想定しているので、遷移前に表示されてた商品とデフォルトで紐づけるような感じが良いでしょうか。
その場合、商品名は入力不可で表示だけするようにすれば良いと考えています。

**Comment by HirokiTakenaka** [comment]
@tantan5 
登録画面UIイメージについて、対象商品の情報を遷移元画面から引き継ぐイメージで変更しました。
上記のファイルリンクにて確認をお願いします。
（レイアウトは適当なので、製造時に必要あれば見直しをお願いします…）

比較表のUIについてはPOからOKをもらってるので、上記確認が問題なければCloseします。

**Comment by tantan5** [comment]
ありがとうございます。
レイアウトとか遷移部分は実装時に調整します。

**Comment by tantan5** [comment]
作りながらの確認になってすみません。
pointとcommentですが、ラフイメージからすると、1つのレコードに3つありそうですが、あってますか？
認識相違なければこちらで足そうと思います。

**Comment by HirokiTakenaka** [comment]
確認ありがとうございます。
1投稿でcomparisonが3レコード作成されるイメージでした(店名-商品名の単位で1レコード)。分かりづらくてすみません。
1レコードに横並びで保持することも有りだと思いますので、実装上やりやすい方でやっていただいて構いません。
