### ISSUE TITLE
データベースの作成（商品比較表）

### ISSUE THREAD

**Issue by HirokiTakenaka** [IshidaHIRO/SDD3#68]
商品基本情報やユーザーが追加する比較項目について、テーブル設計と作成を実施します。
（ちなみに今日仕事休みです）

- [x] テーブル設計
- [x] railsでのRDB作成方法の調査
- [x] テーブル作成

**Comment by HirokiTakenaka** [comment]
## テーブル設計
* テーブル名：「論理名（物理名）」
* フィールド定義：「論理名　物理名　型　凡例　[PK・FK（主キーや外部キー）]」
* 現時点で正規化はあまりしていません（方向性が少し見えないので）
### 商品基本テーブル（items）
1. 店名　shop　varchar　ファミマ　PK
1. 分類　category　varchar　チキン　PK
1. 商品　item　varchar　サラダチキン　PK
1. 商品名　name　varchar　国産鶏のサラダチキン
1. 価格　price　integer　100
1. 熱量　calorie　integer　100
1. 分量　net　integer　100
1. タンパク質　protein　integer　100
1. 脂質　fat　integer　100
1. 炭水化物　carbon　integer　100
1. 糖質　sugar　integer　100
1. 食物繊維　fiber　integer　100
1. ナトリウム　sodium　integer　100
1. 登録日時　registered　timestamp　2016-10-31 10:30:26
1. 更新日時　modified　timestamp　2016-10-31 10:30:26
※脂質とかも下記比較項目テーブル側に含めるかは次スプリント以降で検討する
※Twitterの件数などはとりあえず含めない

### 比較項目テーブル（comparisons）
1. 店名　shop　varchar　ファミマ　PK（←items）
1. 分類　category　varchar　チキン　PK（←items）
1. 商品　item　varchar　サラダチキン　PK（←items）
1. ユーザ名　user　varchar　ファミマニア　PK
1. 比較項目　comparison　varchar　ツヤ　PK
1. 評価タイプ　type　smallint 　0:大きい方が良い、1:小さい方が良い　PK
1. 点数　point　integer　100
1. コメント　coment　varchar　見るからにツヤツヤ
1. 登録日時　registered　timestamp　2016-10-31 10:30:26
1. 更新日時　modified　timestamp　2016-10-31 10:30:26

**Comment by HirokiTakenaka** [comment]
## railsでのRDB作成方法
* 基本的には授業で使用したscaffoldを使用する
[授業ページ](https://github.com/ychubachi/collaborative_development/blob/master/slides/collaborative_development.org#第6章-dbを使うアプリの開発と継続的統合)
* 1対多のリレーション指定にはhas_manyとbelongs_toを使用する
[Rails4で1対多のリレーションをモデルに実装する](http://ruby-rails.hatenadiary.com/entry/20141203/1417601540)

**Comment by takahashiko** [comment]
- has_manyとbelongs_toは始めてですが了解です。 :+1:

**Comment by HirokiTakenaka** [comment]
scaffoldよく分からず苦戦しましたがテーブル作成しました。いくつか補足を。

* 主キーは自動でidというカラムが作成される
* カラム：id、登録日、更新日は自動で作成される
* 複合キー（複数カラムの組み合わせで主キーとする）は基本的に対応していないよう
* heroku上にテーブルを作成する為には、「push heroku」の後に「heroku run rake db:migrate」を実行する必要がある
* 外部キー制約やろうとしたけどよく分からず（とりあえず現時点では無くても問題ないかと）
