### ISSUE TITLE
ダミーの比較表を表示する

### ISSUE THREAD

**Issue by IshidaHIRO** [IshidaHIRO/SDD3#72]

**Comment by IshidaHIRO** [comment]
商品選択メニューの回り込み分を
左にずらして表示させたいのですが、上手くいっていないです。

私のheroku
https://afternoon-river-88035.herokuapp.com/

最悪これでもデモできますが、受け入れ条件を満たしていないかと思います。
詳しい方がいましたら、ご教示ください。

**Comment by HirokiTakenaka** [comment]
@IshidaHIRO @gittkrd 
残となっていたユーザー名の表示について、#76 の方でやろうとしたのですが、
htmlの構成など解析に少し時間がかかりそうだったのでやめました。すみません。
明日明後日などで着手可能でしたら @gittkrd さんか他の方に巻取りをお願いできれば幸いです。
（当初html・CSS側やられてたので私がやるよりも容易かなと考えています）
