### ISSUE TITLE
DBの情報から比較表を表示する

### ISSUE THREAD

**Issue by HirokiTakenaka** [IshidaHIRO/SDD3#76]
comparisonsテーブルからデータを取得し、オリジナル比較表に表示する処理を実装する。

- [x] railsでDBからデータを取得する方法の調査
- [x] 比較表を表示する処理の実装

**Comment by HirokiTakenaka** [comment]
@takahashiko 
とりあえず実装方法の調査までやります。実装作業なかなか着手難しそうでしたら私の方で巻き取りますので、お気軽にお申し付けください（実装やるとすれば明日以降）。

**Comment by HirokiTakenaka** [comment]
scaffoldでrailsのmodelを作成した時点で、comparisonを抽出などする処理は各Controllerから使用できるのかなと理解しています。そうすると基本的には下記のような方法でやれるのかなと思ってます。

## 実装方法
### WelcomeController
* indexでページロード時にセットされるitem（サラダチキンとか）を条件にcomparisonを検索し、条件に合致するレコードをインスタンス変数に格納する（@comparisonsなど）  
→ whereメソッドを使用（Comparison.where(item: item) ※後ろのitemはページロード時にセットされるやつ）

### index.html.erb
* 取得した@comparisonsをeachで読み込みながら、取得件数分の比較表を表示する


次点として、下記のようなところの考慮が必要かと。
* データ未取得時の考慮
* いいね件数の降順でソート

## 参考
* [Railsのモデル検索あれこれ](http://qiita.com/tono0123/items/576a4a4659b51860f304)
* [Railsで共通メソッドの作り方](http://whitech0c0late.hatenablog.com/entry/20120128/1327759552)  
　※共通メソッドのは某メンターより（今回は共通メソッド作らなくても対応出来るかな）

**Comment by HirokiTakenaka** [comment]
#72 で残課題とされていたユーザー名の表示と合わせて、index.html.erb側の製造に着手したいと思います。
Comparison型のインスタンス変数@comparisonsにDB検索結果を格納する想定で、
それをeachで読み込みながら表示する想定です。

差し支えなければ @takahashiko さんの方でWelcomeController側の製造を実施をお願いできればと思います。
（着手済みだったら取り下げますのでお申し付けください）

**Comment by takahashiko** [comment]
@HirokiTakenaka
よろしくお願いいたします。コントローラ側は頑張って見ますが、ご期待に添えない可能性が。
ひとまず、帰ったら対応して見ます。

**Comment by HirokiTakenaka** [comment]
@takahashiko 中途半端な感じですがとりあえずDBの全件表示させるように書いてしまいました。検索条件の指定など残がありますので、私がpushしたブランチをpullしてきて追加作業をお願いできればと思います。
今日のところはここまでにします。
以下、 #78 の方で。
